# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "26d51e19d249be933e36a88e3cfccf8e"
name = "rails8new_shopappgem_b"
handle = "rails8new_shopappgem_b"
application_url = "https://quetzal-definite-sharply.ngrok-free.app"
embedded = true

[build]
dev_store_url = "tyghs-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://quetzal-definite-sharply.ngrok-free.app/auth/shopify/callback" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
